spring.datasource:
  
spring:
  #DB??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/around-hub
    username: myadmin
    password: password
  #JPA??
  jpa:
    hibernate:
      #??????
      ddl-auto: update
    #SQL??
    show-sql: true
    
    properties:
      hibernate:
        # JAP????SQL??
        show_sql: true
        # SQL?????
        format_sql: true 
      
  # ??????????????
  sql:
    init:
      mode: always #always:????????never??????
      schema-locations: classpath:schema.sql #DB????????
      data-locations: classpath:data.sql #DB???????

# Logging
logging:
  level:
    # JPA??????????? 
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace
   
