spring:
  #DB設定
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/around-hub
    username: myadmin
    password: password
  #JPA設定
  jpa:
    hibernate:
      #サーバ起動時にDDL自動実行
      ddl-auto: update
    #SQLを見せる
    show-sql: true

    properties:
      hibernate:
        # JPA実行時のSQL表示
        show_sql: true
        # SQLを自動フォーマット
        format_sql: true

  # DDL自動実行設定
  sql.init:
    mode: always #always: 起動時は必ず実行
    schema-locations: classpath:schema.sql #実行するスキマーファイル
    data-locations: classpath:data.sql #実行するSQLファイル

# Logging
logging.level:
    # JPAログレベル
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace

short.url.x.rapidapi:
  access:
    point: https://url-shortener-service.p.rapidapi.com
    path: shorten
  key: 164f928ba5mshf23a1495c0c62a1p106b49jsnb6ada11dd2ca
  host: url-shortener-service.p.rapidapi.com